name: receipes_app
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  duration: ^2.0.0
  firebase_core: ^0.4.0+9
#  firebase_analytics: ^5.0.2
#  firebase_auth: ^0.6.2+1
#  google_sign_in: ^3.2.2
#  cloud_firestore: ^0.12.9+5
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/brooke-lark-wMzx2nBdeng-unsplash.jpg
    - assets/g-logo.png
  fonts:
    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather-Regular.ttf
    - family: Roboto-Medium
      fonts:
        - asset: fonts/Roboto-Medium.ttf
  uses-material-design: true


